version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "sebassz"
    reviewers:
      - "sebassz"
    labels:
      - "type/dependency"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "daily"
    assignees:
      - "sebassz"
    reviewers:
      - "sebassz"
    labels:
      - "type/dependency"
